name: nlp

dependencies:
  - python=3.7
  - numpy
  - pandas
  - nomkl
  - boto
  - requests
  - pillow
  - matplotlib
  - scikit-learn
  - nltk
  - pip:
    - wordcloud
    - tldextract
    - gensim
